In [2]:
# pandas is a library contains the function of the database
import pandas as pd

In [3]:
dataset=pd.read_csv("Salary_Data.csv") # dataset read the database. here .csv is comma seperated value

In [4]:
dataset # All databases are stored into the dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
#input and output split

In [5]:
#from the database seperating the input data and to get seperate column from the table use [[" "]]
independent=dataset[["YearsExperience"]] 
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [6]:
# from the database seperating the output data
dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [8]:
# sklearn is a library supports in Machine Learning here selecting the model from sklearn to import train_test_split 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0) 
# seperating the actual input and actual output parameter in x_train and Y_train.
# X_test and y_test assigning for user given input and predicted output.

In [11]:
X_train,X_test,Y_train,y_test

(    YearsExperience
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,
     YearsExperience
 2               1.5
 28             10.3
 13              4.1
 10              3.9
 26              9.5
 24              8.7
 27              9.6
 11              4.0
 17              5.3,
       Salary
 22  101302.0
 5    56642.0
 16   66029.0
 8    64445.0
 14   61111.0
 23  113812.0
 20   91738.0
 1    46205.0
 29  121872.0
 6    60150.0
 4    39891.0
 18   81363.0
 19   93940.0
 9    57189.0
 7    54445.0
 25  105582.0
 3    43525.0
 0    39343.0
 21   98273.0
 15   67938.0
 12   56957.0,
       Salary
 2    37731.0
 28  122391.0
 13   57081.0
 10   63218.0
 26  116969.0
 24  109431.0
 27  112635.0
 11   55794.0
 17   83088.0)

In [ ]:
# Model creation

In [13]:
# from linear modelz importing linear regression
from sklearn.linear_model import LinearRegression
regressor=LinearRegression() # regressor assigning the linearregression as a class type
regressor.fit(X_train,Y_train) # regressor access to fit the acutal input and output once it get accessed the slope(weight W) and the bais (b) value had been calculated once it done the model is created

LinearRegression()

In [14]:
weight=regressor.coef_    #weight to check the slope value of the database by using coef_ function
weight

array([[9360.26128619]])

In [17]:
bais=regressor.intercept_  #bais to check the origin or intercept or initial value of the database by using intercept_
bais

array([26777.3913412])

In [18]:
Y_pred=regressor.predict(X_test)  #To cross check predicted output from x_test

In [ ]:
# Validating metrics

In [20]:
from sklearn.metrics import r2_score  #by using r2_score from metrics method validating the model which is created
r_score=r2_score(y_test,Y_pred)

In [21]:
r_score  # the result shows nearly to 1 the model is good if it is nearly to 0 the model is poor

0.9740993407213511

In [22]:
import pickle  # pickle is the function name to save the model and the exension is .sav it is mandatory
filename="finalized_model_linear.sav"  # filname created

In [23]:
pickle.dump(regressor,open(filename,'wb'))  #file created, wb is write binary

In [24]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))  #loaded model assigning to load the file to get predicted output, rb is read binary
result=loaded_model.predict([[15]]) #finally the result shows the predicted output for user given input

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [25]:
result #final result

array([[167181.3106341]])