In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [11]:
indep=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error','friedman_mse','absolute_error'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose= 3, n_jobs=-1)
grid.fit(indep,dep)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [13]:
re=grid.cv_results_
print("the R2_score value for best parameter{}:".format(grid.best_params_))

the R2_score value for best parameter{'criterion': 'absolute_error', 'splitter': 'best'}:

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024992,0.002438,0.010224,0.005949,squared_error,best,"{'criterion': 'squared_error', 'splitter': 'be...",0.714564,0.663002,0.728220,0.697500,0.659523,0.692562,0.027369,4
1,0.019012,0.005357,0.020816,0.013071,squared_error,random,"{'criterion': 'squared_error', 'splitter': 'ra...",0.692827,0.540103,0.670911,0.703518,0.715214,0.664515,0.063894,5
2,0.023429,0.003410,0.008194,0.001263,friedman_mse,best,"{'criterion': 'friedman_mse', 'splitter': 'best'}",0.724418,0.644501,0.728493,0.739227,0.679678,0.703263,0.035740,3
3,0.015689,0.003955,0.009487,0.001914,friedman_mse,random,"{'criterion': 'friedman_mse', 'splitter': 'ran...",0.644268,0.514989,0.740264,0.684426,0.640218,0.644833,0.074237,6
4,0.110853,0.015311,0.015537,0.010699,absolute_error,best,"{'criterion': 'absolute_error', 'splitter': 'b...",0.741590,0.620831,0.743053,0.719812,0.746233,0.714304,0.047661,1
5,0.055413,0.002931,0.007052,0.001436,absolute_error,random,"{'criterion': 'absolute_error', 'splitter': 'r...",0.711076,0.682200,0.716658,0.752112,0.691853,0.710780,0.024158,2

In [19]:
age_input=float(input("Age:"))
BMI_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 34
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [22]:
Future_Prediction=grid.predict([[age_input,BMI_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction{}".format(Future_Prediction))

Future_prediction[4058.71245]

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(